### ISSUE TITLE
Only Port Townsend working on Orcasound staging.

### ISSUE THREAD

**Issue by jd-r** [orcasound/orcasite#31]
The only live audio that works on dev.orcasound.net is Port Townsend. When you click on other hydrophone nodes (e.g. Bush Point or Orcasound Lab), nothing happens.

**Comment by kunakl07** [comment]
Hi @jd-r,
I think that the live audio works for all three of them. I believe that it might be due to silence you may have found the audio not working.
I will share the links to three of them so that you can have a closer look.
[Bush-point](http://live.orcasound.net/bush-point):
[Port-Townsend]( http://live.orcasound.net/port-townsend)
[Haro-Strait]( http://live.orcasound.net/orcasound-lab )

**Comment by scottveirs** [comment]
Hey @jd-r and @kunakl07 -- I don't think you'll need to do this for your summer project, but to use dev.orcasound.net you need to put a node into dev mode. (See the node type environmental variable in the orcanode repo...) That will change the S3 upload destination bucket to dev-streaming instead of live-streaming, so you can do end-to-end testing without disrupting the public live feeds at live.orcasound.net or beta.orcasound.net.

To understand this better, take a look at the diagram here -- 
[https://github.com/orcasound/orcanode](https://github.com/orcasound/orcanode)
